#ifndef CHARTS_HTML_H
#define CHARTS_HTML_H

const char charts_html[] =
"<!DOCTYPE html>\n"
"<html lang=\"pt-br\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Estação Meteorológica - Gráficos</title>\n"
"    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n"
"    <script src=\"https://cdn.tailwindcss.com\"></script>\n"
"</head>\n"
"<body class=\"bg-gray-100 font-sans\">\n"
"    <div class=\"container mx-auto p-4\">\n"
"        <h1 class=\"text-3xl font-bold text-gray-700 mb-6 text-center\">Gráficos em Tempo Real</h1>\n"
"        <div class=\"bg-white p-6 rounded-lg shadow-md\">\n"
"            <div class=\"grid grid-cols-1 lg:grid-cols-3 gap-6\">\n"
"                <div>\n"
"                    <h3 class=\"text-center font-medium text-gray-600\">Temperatura (&deg;C)</h3>\n"
"                    <div class=\"relative h-64\"><canvas id=\"temperatureChart\"></canvas></div>\n"
"                </div>\n"
"                <div>\n"
"                    <h3 class=\"text-center font-medium text-gray-600\">Umidade (%)</h3>\n"
"                    <div class=\"relative h-64\"><canvas id=\"humidityChart\"></canvas></div>\n"
"                </div>\n"
"                <div>\n"
"                    <h3 class=\"text-center font-medium text-gray-600\">Altitude (m)</h3>\n"
"                    <div class=\"relative h-64\"><canvas id=\"altitudeChart\"></canvas></div>\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"        <div class=\"text-center mt-8\">\n"
"           <a href=\"/\" class=\"px-6 py-3 bg-blue-600 text-white font-bold rounded-lg shadow-md hover:bg-blue-700\">Voltar à Página Principal</a>\n"
"        </div>\n"
"    </div>\n"
"    <script>\n"
"        const MAX_DATA_POINTS = 30;\n"
"        let tempChart, humidityChart, altitudeChart;\n"
"        function createChart(elId,label,bColor,bgColor){const ctx=document.getElementById(elId).getContext('2d');return new Chart(ctx,{type:'line',data:{labels:[],datasets:[{label:label,data:[],borderColor:bColor,backgroundColor:bgColor,borderWidth:2,fill:true,tension:0.4,pointRadius:2}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:false}},plugins:{legend:{display:false}}}});}\n"
"        function addDataToChart(chart,label,data){chart.data.labels.push(label);chart.data.datasets[0].data.push(data);if(chart.data.labels.length>MAX_DATA_POINTS){chart.data.labels.shift();chart.data.datasets[0].data.shift();}chart.update('quiet');}\n"
"        function updateCharts(){fetch('/dados').then(r=>r.json()).then(data=>{const now=new Date().toLocaleTimeString();addDataToChart(tempChart,now,data.temperatura_aht);addDataToChart(humidityChart,now,data.umidade);addDataToChart(altitudeChart,now,data.altitude);});}\n"
"        window.onload=function(){tempChart=createChart('temperatureChart','Temperatura','rgba(239,68,68,1)','rgba(239,68,68,0.2)');humidityChart=createChart('humidityChart','Umidade','rgba(59,130,246,1)','rgba(59,130,246,0.2)');altitudeChart=createChart('altitudeChart','Altitude','rgba(16,185,129,1)','rgba(16,185,129,0.2)');updateCharts();setInterval(updateCharts,2000);}\n"
"    </script>\n"
"</body></html>";

#endif