#ifndef INDEX_HTML_H
#define INDEX_HTML_H

const char index_html[] =
"<!DOCTYPE html>\n"
"<html lang=\"pt-br\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Estação Meteorológica - Principal</title>\n"
"    <script src=\"https://cdn.tailwindcss.com\"></script>\n"
"</head>\n"
"<body class=\"bg-gray-100 font-sans\">\n"
"    <div class=\"container mx-auto p-4\">\n"
"        <h1 class=\"text-3xl font-bold text-gray-700 mb-6 text-center\">Estação Meteorológica</h1>\n"
"        <div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\">\n"
"            <div class=\"bg-white p-6 rounded-lg shadow-md\">\n"
"                <h2 class=\"text-xl font-semibold mb-4 text-gray-800\">Dados Atuais</h2>\n"
"                <div class=\"space-y-2\">\n"
"                   <p><strong>Temperatura BMP280:</strong> <span id=\"temp_bmp\">--</span> &deg;C</p>\n"
"                   <p><strong>Temperatura AHT20:</strong> <span id=\"temp_aht\">--</span> &deg;C</p>\n"
"                   <p><strong>Umidade:</strong> <span id=\"humidity\">--</span> %</p>\n"
"                   <p><strong>Altitude:</strong> <span id=\"altitude\">--</span> m</p>\n"
"                </div>\n"
"            </div>\n"
"            <div class=\"bg-white p-6 rounded-lg shadow-md\">\n"
"                <h2 class=\"text-xl font-semibold mb-4 text-gray-800\">Configurar Alerta Laranja</h2>\n"
"                <div class=\"flex items-end gap-4\">\n"
"                    <div class=\"flex-grow\">\n"
"                        <label for=\"orange_min_input\" class=\"block text-sm font-medium text-gray-700\">Mínimo (%):</label>\n"
"                        <input type=\"number\" id=\"orange_min_input\" step=\"0.1\" min=\"0\" max=\"100\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm\">\n"
"                    </div>\n"
"                    <div class=\"flex-grow\">\n"
"                        <label for=\"orange_max_input\" class=\"block text-sm font-medium text-gray-700\">Máximo (%):</label>\n"
"                        <input type=\"number\" id=\"orange_max_input\" step=\"0.1\" min=\"0\" max=\"100\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm\">\n"
"                    </div>\n"
"                    <button onclick=\"setLimits()\" class=\"px-4 py-2 bg-blue-600 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700\">Salvar</button>\n"
"                </div>\n"
"                \n"
"                <div class=\"mt-4 border-t pt-4\">\n"
"                   <p class=\"text-sm\"><strong>Mínimo Atual:</strong> <span id=\"orange_min\">--</span> %</p>\n"
"                   <p class=\"text-sm\"><strong>Máximo Atual:</strong> <span id=\"orange_max\">--</span> %</p>\n"
"                </div>\n"
"                <p id=\"status\" class=\"mt-2 text-sm font-medium\"></p>\n"
"            </div>\n"
"        </div>\n"
"        <div class=\"text-center mt-8\">\n"
"           <a href=\"/charts.html\" class=\"px-6 py-3 bg-green-600 text-white font-bold rounded-lg shadow-md hover:bg-green-700\">Ver Gráficos</a>\n"
"        </div>\n"
"    </div>\n"
"    <script>\n"
"        function updateData() {\n"
"            fetch('/dados').then(r => r.json()).then(data => {\n"
"                document.getElementById('temp_bmp').textContent = data.temperatura_bmp.toFixed(1);\n"
"                document.getElementById('temp_aht').textContent = data.temperatura_aht.toFixed(1);\n"
"                document.getElementById('humidity').textContent = data.umidade.toFixed(1);\n"
"                document.getElementById('altitude').textContent = data.altitude.toFixed(0);\n"
"                // LINHAS ADICIONADAS PARA ATUALIZAR OS VALORES\n"
"                document.getElementById('orange_min').textContent = data.orange_min.toFixed(1);\n"
"                document.getElementById('orange_max').textContent = data.orange_max.toFixed(1);\n"
"            });\n"
"        }\n"
"        function setLimits() {\n"
"            const min = parseFloat(document.getElementById('orange_min_input').value);\n"
"            const max = parseFloat(document.getElementById('orange_max_input').value);\n"
"            const s = document.getElementById('status');\n"
"            if(isNaN(min)||isNaN(max)||min<0||max>100||min>=max){s.textContent='Valores inválidos';s.style.color='red';return;}\n"
"            fetch('/set_orange_limits',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`orange_min=${min}&orange_max=${max}`})\n"
"            .then(r=>{if(r.ok){s.textContent='Salvo!';s.style.color='green';updateData();}else{throw new Error()}}).catch(e=>{s.textContent='Erro!';s.style.color='red';});\n"
"        }\n"
"        window.onload = updateData;\n"
"        setInterval(updateData, 5000);\n"
"    </script>\n"
"</body></html>";

#endif